# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:


jobs:
  compile:
    name: VCPKG DEBUG
    runs-on: ubuntu-latest
    steps:
    - name: Install package
      run: |
        sudo apt-get update
        sudo apt-get install perl autoconf-archive ninja-build cmake pkg-config
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        vcpkg/bootstrap-vcpkg.sh
        env
    - name: Install grpc
      run: |
          set +e
          vcpkg/vcpkg install grpc
          echo "***** debug *****"
          cat /home/runner/work/vcpkg_debug/vcpkg_debug/vcpkg/buildtrees/grpc/config-x64-linux-dbg-CMakeCache.txt.log
          echo "***** release *****"
          cat /home/runner/work/vcpkg_debug/vcpkg_debug/vcpkg/buildtrees/grpc/config-x64-linux-rel-CMakeCache.txt.log
          echo "***** general *****"
          cat /home/runner/work/vcpkg_debug/vcpkg_debug/vcpkg/buildtrees/grpc/config-x64-linux-out.log
