# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:


jobs:
  compile:
    name: VCPKG DEBUG
    runs-on: ubuntu-latest
    steps:
    - name: Install package
      run: |
        sudo apt-get update
        sudo apt-get install perl autoconf-archive ninja-build cmake pkg-config
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        vcpkg/bootstrap-vcpkg.sh
        env
    - name: Install grpc
      run: |
          vcpkg/vcpkg install re2
        
