# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:


jobs:
  compile:
    name: VCPKG DEBUG
    runs-on: ubuntu-latest
    container:
      image: almalinux:8.9
    steps:
    - name: Setup dev environment
      run: |
         dnf update -y && dnf install -y epel-release && dnf config-manager --enable epel && dnf install -y yum-utils && dnf config-manager --set-enabled powertools 
         dnf install -y  git gcc-toolset-13 cmake curl zip unzip tar scl-utils
         yum groupinstall -y 'Development Tools'
         echo "source /opt/rh/gcc-toolset-13/enable" >> ~/.bash_profile
         echo "source ~/.bash_profile" >> ~/.bashrc
         g++ -v
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        vcpkg/bootstrap-vcpkg.sh
    - name: Install grpc\
      env:
          CC: gcc
          CXX: g++
      run: |
          source ~/.bashrc
          vcpkg/vcpkg install boost-cobalt
          
